services:
  mc-demon-api:
    image: rotmayer/mc-b:0.0.2
    container_name: mc-b
    ports:
      - '5010:5010'
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:5010

  mc-demon-frontend:
    image: rotmayer/mc-f:0.0.5
    container_name: mc-f
    volumes:
      - ./dist:/app/dist
    env_file:
      - ~/Desktop/mc-demon-front/.env.developement
    depends_on:
      - mc-demon-api
