services:
  mc-demon-api:
    image: rotmayer/mc-b:latest
    container_name: mc-b
    ports:
      - "5010:5010"
    volumes:
      - ./sources:/app/sources
    environment:
      - ASPNETCORE_URLS=http://+:5010

  mc-demon-frontend:
    image: rotmayer/mc-f:latest    
    container_name: mc-f
    ports:
      - "8080:80"
    depends_on:
      - mc-demon-api